### PR TITLE
WIP: Proposing changes to core/connection module

### PR DESCRIPTION
**Pull request by cb0s**
The connection module is less than ideal especially regarding the consistency.

This proposal introduces a consistent way of sending received connection data via the bus to all verticles which need it. As all incoming connection-data at least consists of a byte-stream and some sender information, this can be used to create one universal ConnectionData-class and let the interfaces create their own participants (e.g. TcpConn.Participant) which implement ConnectionDetails.
ConnectionType then helps to provide the parsing-class for the participants, which can be achieved via reflection.

Please tell me what you think about this.

Note: This is WIP and should neither be merged nor be seen as final.

### CODE REVIEW

**Review by jvpichowski — COMMENTED** [review]
I don't get what problem you want to solve and how you are doing it. Maybe a simple example in the examples module would be fine or an overview drawing. 
Because this got so complex it could be an idea to split the PR into multiple smaller ones.

Besides, your code doesn't build and it has some links to some ancient packages named `old`.

**Comment by jvpichowski** [comment]
>  ConnectionType then helps to provide the parsing-class for the participants, which can be achieved via reflection.

Maybe you are thinking the wrong way round. To decouple things the information which parsing class is used is defined in the configuration file. But I don't know for sure. A small use-case example would be great.

**Comment by cb0s** [comment]
Yes this doesn't build at the moment and I am aware of the old packages. That's why this is still WIP/Draft.

I will add documentation soon, that should clarify what I want to do.

**Review by jvpichowski — COMMENTED** [review]
I like your progress. 

Please add a simple example, in the end, to verify that the overall design works out.

I would replace the Tuple with a local or an inner class but this is a story for another day.

**Comment by cb0s** [comment]
Closed with #266

**Pull request closed without merging**
